Merged PR 3735: Pipeline Upgrade
Enables the schema pipeline to deploy successfully within HA non prod environment.  This includes moving the contexts to behind a cloudfront distribution.

Related work items: #8912

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -5,15 +5,9 @@ pr:
   - main
   - develop
 
-parameters:
-  - name: ENV
-    displayName: Deployment environment
-    default: default
-    values:
-      - default
-      - dev
-      - test
-      - preprod
+
+pool:
+  name: Cloud-bcz-pub
 
 variables:
   CI: 'true'
@@ -21,37 +15,41 @@ variables:
   isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
   isPR: $[eq(variables['Build.Reason'], 'PullRequest')]
   ${{ if eq(variables.isMain, 'true') }}:
-    TARGET_ENV: test # deploy master to test environment
+    TARGET_ENV: e4 # deploy master to test environment
   ${{ elseif eq(variables.isDevelop, 'true') }}:
-    TARGET_ENV: dev # deploy develop to dev environment
-  ${{ elseif ne(parameters.ENV, 'default')}}:
-    TARGET_ENV: ${{ parameters.ENV }} # ENV parameter overrides TARGET_ENV if set
+    TARGET_ENV: e1 # deploy develop to e1 environment
   ${{ else }}:
-    TARGET_ENV: dev # set default TARGET_ENV to dev
+    TARGET_ENV: e1 # set default TARGET_ENV to e1
   ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
+    NX_BRANCH: $(System.PullRequest.PullRequestNumber)
     TARGET_BRANCH: $[replace(variables['System.PullRequest.TargetBranch'],'refs/heads/','origin/')]
     BASE_SHA: main
   ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
+    NX_BRANCH: $(Build.SourceBranchName)
     BASE_SHA: main~1
   HEAD_SHA: $(git rev-parse HEAD)
 
 stages:
-  - stage: build_test
-    pool:
-      vmImage: ubuntu-latest
-    variables:
-      disable.coverage.autogenerate: true
+  - stage: build
     jobs:
-      - job: build_test
+      - job: build
         steps:
+          - script: |
+              df -h
+              SIZE=$(df -hP / | awk '{print ($4 * 1024)}' |tail -1)
+
+              if [ $SIZE -lt 3000 ]
+              then
+                  echo "Agent does not have enough disk space to continue."
+                  exit 1
+              fi
+            displayName: 'Check disk size'
+
           - checkout: self
             fetchDepth: 2
             displayName: Checkout
 
-          - task: NodeTool@0
-            displayName: Set Node Version
-            inputs:
-              versionSpec: 14.x
+          - template: .azure-pipelines/steps/install-node-modules.yml
 
           - bash: |
               make install
@@ -72,20 +70,20 @@ stages:
               failTaskOnFailedTests: true
             displayName: Publish test results to AzDo
 
-          - task: reportgenerator@5
-            inputs:
-              reports: '**/cobertura-coverage.xml'
-              reporttypes: 'HtmlInline_AzurePipelines;Cobertura'
-              targetdir: '$(System.DefaultWorkingDirectory)/Coverage'
-            displayName: 'Generate code coverage results'
+#          - task: reportgenerator@5
+#            inputs:
+#              reports: '**/cobertura-coverage.xml'
+#              reporttypes: 'HtmlInline_AzurePipelines;Cobertura'
+#              targetdir: '$(System.DefaultWorkingDirectory)/Coverage'
+#            displayName: 'Generate code coverage results'
 
-          - task: PublishCodeCoverageResults@1
-            inputs:
-              codeCoverageTool: 'Cobertura'
-              summaryFileLocation: '$(System.DefaultWorkingDirectory)/Coverage/Cobertura.xml'
-              reportDirectory: '$(System.DefaultWorkingDirectory)/Coverage'
-              failTaskOnFailedTests: true
-            displayName: Publish code coverage results to AzDo
+#          - task: PublishCodeCoverageResults@1
+#            inputs:
+#              codeCoverageTool: 'Cobertura'
+#              summaryFileLocation: '$(System.DefaultWorkingDirectory)/Coverage/Cobertura.xml'
+#              reportDirectory: '$(System.DefaultWorkingDirectory)/Coverage'
+#              failTaskOnFailedTests: true
+#            displayName: Publish code coverage results to AzDo
 
           - bash: |
               make build
@@ -107,58 +105,56 @@ stages:
               targetPath: $(System.DefaultWorkingDirectory)/schemas
               artifactName: 'schemas'
   - stage: deploy
-    dependsOn: build_test
+    dependsOn: build
     condition: and(succeeded(), or(eq(variables.isMain, 'true'), eq(variables.isDevelop, 'true')))
-    pool:
-      vmImage: ubuntu-latest
     jobs:
-      - job: deploy
-        steps:
-          - script: |
-              echo "Deployment environment: ${{variables.TARGET_ENV}}"
+    - deployment: DeploySchema
+      displayName: deploy Schema
+      environment: ${{ variables.TARGET_ENV }}
+      strategy:
+        runOnce:
+          deploy:
+            steps:
+            - script: df -h
+              displayName: 'Check disk size'
 
-          - task: AzureKeyVault@2
-            inputs:
-              connectedServiceName: 'gs-ha-dvp-serviceconnection'
-              keyVaultName: 'gs-ha-dvp'
-              secretsFilter: '*'
-              runAsPreJob: true
+            - task: DownloadPipelineArtifact@2
+              inputs:
+                source: 'current' # Options: current, specific
+                path: $(System.DefaultWorkingDirectory)/artifacts
 
-          - task: DownloadPipelineArtifact@2
-            inputs:
-              source: 'current' # Options: current, specific
-              path: $(System.DefaultWorkingDirectory)/artifacts
+            - template: .azure-pipelines/steps/install-node-modules.yml
 
-          - task: NodeTool@0
-            displayName: Set Node Version
-            inputs:
-              versionSpec: 14.x
+            - task: AWSShellScript@1
+              displayName: Setup pulumi
+              env:
+                ENV: ${{ variables.TARGET_ENV }}
+              inputs:
+                awsCredentials: 'aws-dvp-nonprod'
+                regionName: 'ap-southeast-2'
+                scriptType: 'inline'
+                inlineScript: |                  
+                  # exit if a command returns a non-zero exit code and also print the commands and their args as they are executed
+                  set -e -x
 
-          - bash: |
-              # exit if a command returns a non-zero exit code and also print the commands and their args as they are executed
-              set -e -x
+                  # Download and install required tools pulumi
+                  sudo rm -rf $HOME/.pulumi
+                  sudo rm -rf /usr/local/bin/pulumi*
+                  curl -fsSL https://get.pulumi.com | sh -s -- --version 3.30.0
+                  sudo /bin/cp -rf $HOME/.pulumi/bin/* /usr/local/bin
 
-              # Download and install required tools pulumi
-              rm -rf $HOME/.pulumi
-              rm -rf /usr/local/bin/pulumi*
-              curl -fsSL https://get.pulumi.com | sh -s -- --version 3.30.0
-              /bin/cp -rf $HOME/.pulumi/bin/* /usr/local/bin
+                  pulumi plugin install resource aws v5.23.0
+                  pulumi plugin install resource synced-folder v0.0.9
 
-              pulumi plugin install resource aws v5.23.0
+                  cd infrastructure && npm install
 
-              cd infrastructure && npm install
-            displayName: Install pulumi
-
-          - bash: |
-              make pulumi-preview
-            displayName: Run `pulumi preview`
-            env:
-              AWS_ACCESS_KEY_ID: $(AWS-ACCESS-KEY-ID)
-              AWS_SECRET_ACCESS_KEY: $(aws-secret-access-key)
-
-          - bash: |
-              make pulumi-up
-            displayName: Run `pulumi up`
-            env:
-              AWS_ACCESS_KEY_ID: $(AWS-ACCESS-KEY-ID)
-              AWS_SECRET_ACCESS_KEY: $(aws-secret-access-key)
+            - task: AWSShellScript@1
+              displayName: Deploy
+              env:
+                ENV: ${{ variables.TARGET_ENV }}
+              inputs:
+                awsCredentials: 'aws-dvp-nonprod'
+                regionName: 'ap-southeast-2'
+                scriptType: 'inline'
+                inlineScript: |
+                  make pulumi-up
